name: Docker Image CI

on:
  push:
    branches: 
      - master
      - release/*
      - mono_ci/*
  pull_request:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: for k in `ls tc_*` ; do 
           docker build $k --file $k/Dockerfile --tag my-image-name:$(date +%s)
           
